name: Release Mobile App
on:
  workflow_dispatch:
    inputs:
      os:
        type: choice
        description: OS to build on. Ubuntu is faster, MacOS supports iOS builds
        options:
          - macos-latest
          - ubuntu-latest
      platform:
        type: choice
        description: Platform to build for
        options:
          - android
          - ios
      profile:
        type: choice
        description: Build profile to use
        options:
          - development
          - preview
          - production
      should_submit:
        type: boolean
        description: Whether to perform the submit step
        required: true
        default: false
jobs:
  release-mobile-app:
    runs-on: ${{github.event.inputs.os}}
    env:
      DOPPLER_CONFIG: ${{ github.event.inputs.profile == 'production' && 'prd' || 'stg' }}
    steps:
      - name: git checkout
        uses: actions/checkout@v3
      - name: Install nix
        uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Check Nixpkgs inputs
        uses: DeterminateSystems/flake-checker-action@main
        with:
          fail-mode: true
      - name: Setup direnv
        uses: HatsuneMiku3939/direnv-action@v1
        with:
          direnvVersion: 2.32.2
      - name: Set up Java
        uses: actions/setup-java@v2
        if: ${{ github.event.inputs.platform }} == "android"
        with:
          java-version: 17
          distribution: "temurin"
      - name: Debug Environment
        run: |
          echo "OS: ${{ github.event.inputs.os }}"
          echo "Platform: ${{ github.event.inputs.platform }}"
          echo "Profile: ${{ github.event.inputs.profile }}"
          echo "Should Submit: ${{ github.event.inputs.should_submit }}"
          pod --version
      - name: Debug CocoaPods Environment
        run: |
          which pod
          pod --version
          xcode-select -p
          xcodebuild -showsdks
      - name: Install packages
        run: pnpm install
      - name: Build app
        run: eas build -p ${{github.event.inputs.platform}} --profile ${{github.event.inputs.profile}} --local --non-interactive --output=./app-build
        working-directory: "apps/mobile-sample"
      - uses: actions/upload-artifact@v4
        if: ${{ github.event.inputs.should_submit }} == false
        with:
          name: ${{github.event.inputs.platform}}-${{github.event.inputs.platform}}
          path: apps/mobile/${{ github.event.inputs.platform }}
      - name: Submit app
        if: ${{ github.event.inputs.should_submit }}
        working-directory: apps/mobile
        run: eas submit -p ${{ github.event.inputs.platform }} --profile ${{ github.event.inputs.profile }} --path app-build
